### YamlMime:ManagedReference
items:
- uid: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig
  commentId: T:BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig
  id: LayeredCharacterTypeSO.CharacterCreatorConfig
  parent: BlazerTech.CharacterManagement.Characters
  children:
  - BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BaseCharacterPieceCollection
  - BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BaseCharacterPieceLoadedSpriteIndex
  - BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPlaceholderSprite
  - BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewController
  - BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewFrameIndex
  - BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.PreviewFrameHeight
  - BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.PreviewFrameWidth
  - BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.UseCleanCharacterPieceNames
  langs:
  - csharp
  - vb
  name: LayeredCharacterTypeSO.CharacterCreatorConfig
  nameWithType: LayeredCharacterTypeSO.CharacterCreatorConfig
  fullName: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig
  type: Class
  source:
    remote:
      path: Assets/BlazerTech Character Management System/Scripts/Scriptable Objects/Character Types/LayeredCharacterTypeSO.cs
      branch: main
      repo: https://github.com/Legendaryswordsman2/BlazerTech-Character-Management-System.git
    id: CharacterCreatorConfig
    path: ../../../Unity/Unity Projects/BlazerTech Character Management System/Assets/BlazerTech Character Management System/Scripts/Scriptable Objects/Character Types/LayeredCharacterTypeSO.cs
    startLine: 126
  assemblies:
  - Assembly-CSharp
  namespace: BlazerTech.CharacterManagement.Characters
  syntax:
    content: >-
      [Serializable]

      public class LayeredCharacterTypeSO.CharacterCreatorConfig
    content.vb: >-
      <Serializable>

      Public Class LayeredCharacterTypeSO.CharacterCreatorConfig
  inheritance:
  - System.Object
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
- uid: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.UseCleanCharacterPieceNames
  commentId: F:BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.UseCleanCharacterPieceNames
  id: UseCleanCharacterPieceNames
  parent: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig
  langs:
  - csharp
  - vb
  name: UseCleanCharacterPieceNames
  nameWithType: LayeredCharacterTypeSO.CharacterCreatorConfig.UseCleanCharacterPieceNames
  fullName: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.UseCleanCharacterPieceNames
  type: Field
  source:
    remote:
      path: Assets/BlazerTech Character Management System/Scripts/Scriptable Objects/Character Types/LayeredCharacterTypeSO.cs
      branch: main
      repo: https://github.com/Legendaryswordsman2/BlazerTech-Character-Management-System.git
    id: UseCleanCharacterPieceNames
    path: ../../../Unity/Unity Projects/BlazerTech Character Management System/Assets/BlazerTech Character Management System/Scripts/Scriptable Objects/Character Types/LayeredCharacterTypeSO.cs
    startLine: 130
  assemblies:
  - Assembly-CSharp
  namespace: BlazerTech.CharacterManagement.Characters
  syntax:
    content: >-
      [Tooltip("Automatically replaces underscores with spaces when displaying character piece names")]

      public bool UseCleanCharacterPieceNames
    return:
      type: System.Boolean
    content.vb: >-
      <Tooltip("Automatically replaces underscores with spaces when displaying character piece names")>

      Public UseCleanCharacterPieceNames As Boolean
  attributes:
  - type: UnityEngine.TooltipAttribute
    ctor: UnityEngine.TooltipAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: Automatically replaces underscores with spaces when displaying character piece names
- uid: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewController
  commentId: F:BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewController
  id: CharacterPreviewController
  parent: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig
  langs:
  - csharp
  - vb
  name: CharacterPreviewController
  nameWithType: LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewController
  fullName: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewController
  type: Field
  source:
    remote:
      path: Assets/BlazerTech Character Management System/Scripts/Scriptable Objects/Character Types/LayeredCharacterTypeSO.cs
      branch: main
      repo: https://github.com/Legendaryswordsman2/BlazerTech-Character-Management-System.git
    id: CharacterPreviewController
    path: ../../../Unity/Unity Projects/BlazerTech Character Management System/Assets/BlazerTech Character Management System/Scripts/Scriptable Objects/Character Types/LayeredCharacterTypeSO.cs
    startLine: 134
  assemblies:
  - Assembly-CSharp
  namespace: BlazerTech.CharacterManagement.Characters
  syntax:
    content: >-
      [Space]

      public RuntimeAnimatorController CharacterPreviewController
    return:
      type: UnityEngine.RuntimeAnimatorController
    content.vb: >-
      <Space>

      Public CharacterPreviewController As RuntimeAnimatorController
  attributes:
  - type: UnityEngine.SpaceAttribute
    ctor: UnityEngine.SpaceAttribute.#ctor
    arguments: []
- uid: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPlaceholderSprite
  commentId: F:BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPlaceholderSprite
  id: CharacterPlaceholderSprite
  parent: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig
  langs:
  - csharp
  - vb
  name: CharacterPlaceholderSprite
  nameWithType: LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPlaceholderSprite
  fullName: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPlaceholderSprite
  type: Field
  source:
    remote:
      path: Assets/BlazerTech Character Management System/Scripts/Scriptable Objects/Character Types/LayeredCharacterTypeSO.cs
      branch: main
      repo: https://github.com/Legendaryswordsman2/BlazerTech-Character-Management-System.git
    id: CharacterPlaceholderSprite
    path: ../../../Unity/Unity Projects/BlazerTech Character Management System/Assets/BlazerTech Character Management System/Scripts/Scriptable Objects/Character Types/LayeredCharacterTypeSO.cs
    startLine: 135
  assemblies:
  - Assembly-CSharp
  namespace: BlazerTech.CharacterManagement.Characters
  syntax:
    content: public Sprite CharacterPlaceholderSprite
    return:
      type: UnityEngine.Sprite
    content.vb: Public CharacterPlaceholderSprite As Sprite
- uid: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BaseCharacterPieceCollection
  commentId: P:BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BaseCharacterPieceCollection
  id: BaseCharacterPieceCollection
  parent: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig
  langs:
  - csharp
  - vb
  name: BaseCharacterPieceCollection
  nameWithType: LayeredCharacterTypeSO.CharacterCreatorConfig.BaseCharacterPieceCollection
  fullName: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BaseCharacterPieceCollection
  type: Property
  source:
    remote:
      path: Assets/BlazerTech Character Management System/Scripts/Scriptable Objects/Character Types/LayeredCharacterTypeSO.cs
      branch: main
      repo: https://github.com/Legendaryswordsman2/BlazerTech-Character-Management-System.git
    id: BaseCharacterPieceCollection
    path: ../../../Unity/Unity Projects/BlazerTech Character Management System/Assets/BlazerTech Character Management System/Scripts/Scriptable Objects/Character Types/LayeredCharacterTypeSO.cs
    startLine: 138
  assemblies:
  - Assembly-CSharp
  namespace: BlazerTech.CharacterManagement.Characters
  syntax:
    content: public CharacterLayerSO BaseCharacterPieceCollection { get; }
    parameters: []
    return:
      type: BlazerTech.CharacterManagement.Characters.CharacterLayerSO
    content.vb: Public Property BaseCharacterPieceCollection As CharacterLayerSO
  overload: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BaseCharacterPieceCollection*
- uid: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BaseCharacterPieceLoadedSpriteIndex
  commentId: P:BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BaseCharacterPieceLoadedSpriteIndex
  id: BaseCharacterPieceLoadedSpriteIndex
  parent: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig
  langs:
  - csharp
  - vb
  name: BaseCharacterPieceLoadedSpriteIndex
  nameWithType: LayeredCharacterTypeSO.CharacterCreatorConfig.BaseCharacterPieceLoadedSpriteIndex
  fullName: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BaseCharacterPieceLoadedSpriteIndex
  type: Property
  source:
    remote:
      path: Assets/BlazerTech Character Management System/Scripts/Scriptable Objects/Character Types/LayeredCharacterTypeSO.cs
      branch: main
      repo: https://github.com/Legendaryswordsman2/BlazerTech-Character-Management-System.git
    id: BaseCharacterPieceLoadedSpriteIndex
    path: ../../../Unity/Unity Projects/BlazerTech Character Management System/Assets/BlazerTech Character Management System/Scripts/Scriptable Objects/Character Types/LayeredCharacterTypeSO.cs
    startLine: 142
  assemblies:
  - Assembly-CSharp
  namespace: BlazerTech.CharacterManagement.Characters
  syntax:
    content: public int BaseCharacterPieceLoadedSpriteIndex { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property BaseCharacterPieceLoadedSpriteIndex As Integer
  overload: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BaseCharacterPieceLoadedSpriteIndex*
- uid: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.PreviewFrameWidth
  commentId: F:BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.PreviewFrameWidth
  id: PreviewFrameWidth
  parent: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig
  langs:
  - csharp
  - vb
  name: PreviewFrameWidth
  nameWithType: LayeredCharacterTypeSO.CharacterCreatorConfig.PreviewFrameWidth
  fullName: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.PreviewFrameWidth
  type: Field
  source:
    remote:
      path: Assets/BlazerTech Character Management System/Scripts/Scriptable Objects/Character Types/LayeredCharacterTypeSO.cs
      branch: main
      repo: https://github.com/Legendaryswordsman2/BlazerTech-Character-Management-System.git
    id: PreviewFrameWidth
    path: ../../../Unity/Unity Projects/BlazerTech Character Management System/Assets/BlazerTech Character Management System/Scripts/Scriptable Objects/Character Types/LayeredCharacterTypeSO.cs
    startLine: 147
  assemblies:
  - Assembly-CSharp
  namespace: BlazerTech.CharacterManagement.Characters
  syntax:
    content: >-
      [Header("Character Piece Preview Settings")]

      public int PreviewFrameWidth
    return:
      type: System.Int32
    content.vb: >-
      <Header("Character Piece Preview Settings")>

      Public PreviewFrameWidth As Integer
  attributes:
  - type: UnityEngine.HeaderAttribute
    ctor: UnityEngine.HeaderAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: Character Piece Preview Settings
- uid: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.PreviewFrameHeight
  commentId: F:BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.PreviewFrameHeight
  id: PreviewFrameHeight
  parent: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig
  langs:
  - csharp
  - vb
  name: PreviewFrameHeight
  nameWithType: LayeredCharacterTypeSO.CharacterCreatorConfig.PreviewFrameHeight
  fullName: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.PreviewFrameHeight
  type: Field
  source:
    remote:
      path: Assets/BlazerTech Character Management System/Scripts/Scriptable Objects/Character Types/LayeredCharacterTypeSO.cs
      branch: main
      repo: https://github.com/Legendaryswordsman2/BlazerTech-Character-Management-System.git
    id: PreviewFrameHeight
    path: ../../../Unity/Unity Projects/BlazerTech Character Management System/Assets/BlazerTech Character Management System/Scripts/Scriptable Objects/Character Types/LayeredCharacterTypeSO.cs
    startLine: 148
  assemblies:
  - Assembly-CSharp
  namespace: BlazerTech.CharacterManagement.Characters
  syntax:
    content: public int PreviewFrameHeight
    return:
      type: System.Int32
    content.vb: Public PreviewFrameHeight As Integer
- uid: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewFrameIndex
  commentId: F:BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewFrameIndex
  id: CharacterPreviewFrameIndex
  parent: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig
  langs:
  - csharp
  - vb
  name: CharacterPreviewFrameIndex
  nameWithType: LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewFrameIndex
  fullName: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.CharacterPreviewFrameIndex
  type: Field
  source:
    remote:
      path: Assets/BlazerTech Character Management System/Scripts/Scriptable Objects/Character Types/LayeredCharacterTypeSO.cs
      branch: main
      repo: https://github.com/Legendaryswordsman2/BlazerTech-Character-Management-System.git
    id: CharacterPreviewFrameIndex
    path: ../../../Unity/Unity Projects/BlazerTech Character Management System/Assets/BlazerTech Character Management System/Scripts/Scriptable Objects/Character Types/LayeredCharacterTypeSO.cs
    startLine: 149
  assemblies:
  - Assembly-CSharp
  namespace: BlazerTech.CharacterManagement.Characters
  syntax:
    content: public int CharacterPreviewFrameIndex
    return:
      type: System.Int32
    content.vb: Public CharacterPreviewFrameIndex As Integer
references:
- uid: BlazerTech.CharacterManagement.Characters
  commentId: N:BlazerTech.CharacterManagement.Characters
  href: BlazerTech.html
  name: BlazerTech.CharacterManagement.Characters
  nameWithType: BlazerTech.CharacterManagement.Characters
  fullName: BlazerTech.CharacterManagement.Characters
  spec.csharp:
  - uid: BlazerTech
    name: BlazerTech
    href: BlazerTech.html
  - name: .
  - uid: BlazerTech.CharacterManagement
    name: CharacterManagement
    href: BlazerTech.CharacterManagement.html
  - name: .
  - uid: BlazerTech.CharacterManagement.Characters
    name: Characters
    href: BlazerTech.CharacterManagement.Characters.html
  spec.vb:
  - uid: BlazerTech
    name: BlazerTech
    href: BlazerTech.html
  - name: .
  - uid: BlazerTech.CharacterManagement
    name: CharacterManagement
    href: BlazerTech.CharacterManagement.html
  - name: .
  - uid: BlazerTech.CharacterManagement.Characters
    name: Characters
    href: BlazerTech.CharacterManagement.Characters.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: UnityEngine.RuntimeAnimatorController
  commentId: T:UnityEngine.RuntimeAnimatorController
  parent: UnityEngine
  isExternal: true
  name: RuntimeAnimatorController
  nameWithType: RuntimeAnimatorController
  fullName: UnityEngine.RuntimeAnimatorController
- uid: UnityEngine
  commentId: N:UnityEngine
  isExternal: true
  name: UnityEngine
  nameWithType: UnityEngine
  fullName: UnityEngine
- uid: UnityEngine.Sprite
  commentId: T:UnityEngine.Sprite
  parent: UnityEngine
  isExternal: true
  name: Sprite
  nameWithType: Sprite
  fullName: UnityEngine.Sprite
- uid: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BaseCharacterPieceCollection*
  commentId: Overload:BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BaseCharacterPieceCollection
  href: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.html#BlazerTech_CharacterManagement_Characters_LayeredCharacterTypeSO_CharacterCreatorConfig_BaseCharacterPieceCollection
  name: BaseCharacterPieceCollection
  nameWithType: LayeredCharacterTypeSO.CharacterCreatorConfig.BaseCharacterPieceCollection
  fullName: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BaseCharacterPieceCollection
- uid: BlazerTech.CharacterManagement.Characters.CharacterLayerSO
  commentId: T:BlazerTech.CharacterManagement.Characters.CharacterLayerSO
  parent: BlazerTech.CharacterManagement.Characters
  href: BlazerTech.CharacterManagement.Characters.CharacterLayerSO.html
  name: CharacterLayerSO
  nameWithType: CharacterLayerSO
  fullName: BlazerTech.CharacterManagement.Characters.CharacterLayerSO
- uid: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BaseCharacterPieceLoadedSpriteIndex*
  commentId: Overload:BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BaseCharacterPieceLoadedSpriteIndex
  href: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.html#BlazerTech_CharacterManagement_Characters_LayeredCharacterTypeSO_CharacterCreatorConfig_BaseCharacterPieceLoadedSpriteIndex
  name: BaseCharacterPieceLoadedSpriteIndex
  nameWithType: LayeredCharacterTypeSO.CharacterCreatorConfig.BaseCharacterPieceLoadedSpriteIndex
  fullName: BlazerTech.CharacterManagement.Characters.LayeredCharacterTypeSO.CharacterCreatorConfig.BaseCharacterPieceLoadedSpriteIndex
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
