name: Deploy versioned docs to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'Versions/**'
      - '_site/**'     # optional: include if you want /latest updated automatically

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare publish directory
        run: |
          mkdir -p public
          # Copy all version folders so they sit at the site root as /v1.0, /v1.1, etc.
          rsync -av --delete "Versions/" "public/"

          # Optional: also expose your current local build at /latest/
          if [ -d "_site" ]; then
            mkdir -p public/latest
            rsync -av --delete "_site/" "public/latest/"
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
