name: Deploy Docs (multi-version + header switcher)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # For project sites, set to /<repo>. For user/org or custom domain, set to /
      BASE_PATH: /DocFX-Version-Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure Versions exists
        run: |
          if [ ! -d "Versions" ]; then
            echo "Versions folder not found. Nothing to deploy." >&2
            exit 1
          fi

      - name: Determine versions (sorted) and latest
        id: versions
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          # Collect folder names like V1.0.0, V1.1.0, etc (strip leading V to sort -V)
          mapfile -t DIRS < <(find Versions -maxdepth 1 -mindepth 1 -type d -printf "%f\n" | sed 's/^V//' | sort -V)
          if [ ${#DIRS[@]} -eq 0 ]; then
            echo "No version folders found in Versions/" >&2
            exit 1
          fi

          LATEST="V${DIRS[-1]}"

          # JSON array like ["V1.0.0","V1.1.0",...]
          JSON_VERSIONS=$(printf '%s\n' "${DIRS[@]}" | sed 's/^/V/' | jq -R . | jq -sc .)

          {
            echo "latest=$LATEST"
            echo "versions<<JSON"
            printf '%s\n' "$JSON_VERSIONS"
            echo "JSON"
          } >> "$GITHUB_OUTPUT"

          echo "Detected versions: $JSON_VERSIONS"
          echo "Latest: $LATEST"

      - name: Build publish tree
        run: |
          mkdir -p _site
          rsync -a Versions/ _site/Versions/
          touch _site/.nojekyll

          # Root index and 404 that redirect to latest
          cat > _site/index.html <<'HTML'
          <!doctype html><meta charset="utf-8">
          <meta http-equiv="refresh" content="0; url=__BASE__/Versions/__LATEST__/">
          <script>location.replace("__BASE__/Versions/__LATEST__/");</script>
          HTML
          sed -i "s|__BASE__|${BASE_PATH}|g" _site/index.html
          sed -i "s|__LATEST__|${{ steps.versions.outputs.latest }}|g" _site/index.html

          cat > _site/404.html <<'HTML'
          <!doctype html><meta charset="utf-8">
          <meta http-equiv="refresh" content="0; url=__BASE__/Versions/__LATEST__/">
          <script>location.replace("__BASE__/Versions/__LATEST__/");</script>
          HTML
          sed -i "s|__BASE__|${BASE_PATH}|g" _site/404.html
          sed -i "s|__LATEST__|${{ steps.versions.outputs.latest }}|g" _site/404.html

          # Optional: expose /latest/ alias (uncomment to enable)
          # rsync -a "_site/Versions/${{ steps.versions.outputs.latest }}/" "_site/latest/"

      - name: Write versions.json
        run: |
          cat > _site/versions.json <<JSON
          {
            "basePath": "${BASE_PATH}",
            "latest": "${{ steps.versions.outputs.latest }}",
            "versions": ${{ steps.versions.outputs.versions }}
          }
          JSON

      - name: Add version switcher JS (navbar integration)
        run: |
          mkdir -p _site/assets/version-switcher
          cat > _site/assets/version-switcher/version-switcher.js <<'JS'
          (async function(){
            try {
              // Detect base and current version from /Versions/Vx.y.z/
              const m = location.pathname.match(/^(.*)\/Versions\/(V[^/]+)\//);
              const basePathFromUrl = m ? m[1] : '';
              const currentVersion = m ? m[2] : null;

              // Load site metadata
              const metaUrl = (basePathFromUrl || '') + '/versions.json';
              const meta = await fetch(metaUrl, { cache: 'no-store' }).then(r => r.json()).catch(()=>null);
              if (!meta) return;

              const basePath = meta.basePath || basePathFromUrl || '';
              const versions = Array.isArray(meta.versions) ? meta.versions.slice() : [];
              const latest = meta.latest || (versions[versions.length-1] || null);

              // Sort semver descending
              versions.sort((a,b)=>{
                const av = a.replace(/^V/,'').split('.').map(Number);
                const bv = b.replace(/^V/,'').split('.').map(Number);
                for (let i=0;i<Math.max(av.length,bv.length);i++){
                  const d = (bv[i]||0)-(av[i]||0);
                  if (d) return d;
                }
                return 0;
              });

              // Build the <select>
              const select = document.createElement('select');
              select.setAttribute('aria-label','Select documentation version');
              select.style.background = 'transparent';
              select.style.color = 'inherit';
              select.style.border = '1px solid rgba(255,255,255,.25)';
              select.style.borderRadius = '4px';
              select.style.padding = '4px 6px';
              select.style.marginLeft = '12px';

              versions.forEach(v=>{
                const opt = document.createElement('option');
                opt.value = v;
                opt.textContent = v + (v===latest ? ' •' : '');
                select.appendChild(opt);
              });
              if (currentVersion && versions.includes(currentVersion)) select.value = currentVersion;
              else if (latest) select.value = latest;

              // Navigate to same relative path in target version; fallback to that version's root
              async function go(v){
                const rest = m ? location.pathname.replace(/^(.*)\/Versions\/(V[^/]+)\//, '') : '';
                const targetSame = `${basePath}/Versions/${v}/${rest}`;
                if (!rest) { location.href = targetSame; return; }
                try {
                  const ok = await fetch(targetSame, { method: 'HEAD', cache: 'no-store' }).then(r => r.ok);
                  location.href = ok ? targetSame : `${basePath}/Versions/${v}/`;
                } catch {
                  location.href = `${basePath}/Versions/${v}/`;
                }
              }
              select.addEventListener('change', e => go(e.target.value));

              // Find a good spot in the Modern theme navbar (try a few patterns)
              // Typical Modern theme structure:
              // <div class="navbar ..."><div class="container"><div id="navbar" class="navbar-collapse collapse"> ... <ul class="nav navbar-nav navbar-right">...</ul></div></div></div>
              let mounted = false;

              function mountRight(item){
                if (!item) return false;
                // Wrap in <li> if targeting a <ul>
                if (item.tagName === 'UL') {
                  const li = document.createElement('li');
                  li.appendChild(select);
                  item.appendChild(li);
                  return true;
                }
                // Otherwise append directly (e.g., a toolbar container)
                item.appendChild(select);
                return true;
              }

              const trySelectors = [
                '.navbar .navbar-collapse .nav.navbar-nav.navbar-right', // preferred
                '.navbar .navbar-collapse .navbar-right',
                '#navbar .nav.navbar-nav.navbar-right',
                '.navbar .navbar-collapse', // broader
                '.navbar .container',       // fallback
                '.navbar'                   // last resort
              ];

              for (const sel of trySelectors) {
                const target = document.querySelector(sel);
                if (target && mountRight(target)) { mounted = true; break; }
              }

              // As a final fallback, add it to the document end (shouldn't happen on Modern)
              if (!mounted) {
                const wrap = document.createElement('div');
                wrap.style.position='fixed';
                wrap.style.top='0'; wrap.style.right='0';
                wrap.style.padding='8px';
                wrap.style.zIndex='99999';
                wrap.style.background='rgba(0,0,0,.6)';
                wrap.style.backdropFilter='blur(6px)';
                wrap.style.color='#fff';
                wrap.style.borderBottomLeftRadius='8px';
                wrap.appendChild(select);
                document.body.appendChild(wrap);
              }
            } catch (e) {
              console.warn('Version switcher failed:', e);
            }
          })();
          JS

      - name: Inject switcher into all version pages
        shell: bash
        run: |
          # Inject the script tag into every HTML file under Versions/**
          find _site/Versions -type f -name '*.html' | while read -r file; do
            # Skip already-injected files
            if grep -q 'assets/version-switcher/version-switcher.js' "$file"; then
              continue
            fi

            if grep -q '</body>' "$file"; then
              awk -v base="${BASE_PATH}" '
                BEGIN{injected=0}
                /<\/body>/ && injected==0 {
                  print "  <script src=\"" base "/assets/version-switcher/version-switcher.js\" defer></script>"
                  injected=1
                }
                {print}
              ' "$file" > "$file.tmp" && mv "$file.tmp" "$file"
            else
              printf '\n<script src="%s/assets/version-switcher/version-switcher.js" defer></script>\n' "${BASE_PATH}" >> "$file"
            fi
          done

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4