name: Deploy DocFX _site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for write access to the repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if _site or docfx.json changed
        id: check_changes
        run: |
          if git diff --quiet HEAD^ HEAD -- _site docfx.json; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Deploy _site folder
        if: steps.check_changes.outputs.changed == 'true'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site